# incident.py
# Auto-generates an incident markdown report when thresholds are breached
# Saves to an /incidents folder so every event is documented

import os
from datetime import datetime

INCIDENTS_FOLDER = "incidents"

def create_incident_report(metric, current_value, threshold):
    """Auto-generate a markdown incident report file."""

    if not os.path.exists(INCIDENTS_FOLDER):
        os.makedirs(INCIDENTS_FOLDER)

    timestamp     = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename      = f"{INCIDENTS_FOLDER}/incident_{metric}_{timestamp}.md"
    readable_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""# Incident Report

| Field        | Detail                          |
|--------------|---------------------------------|
| **Metric**   | {metric.upper()}                |
| **Value**    | {current_value}%                |
| **Threshold**| {threshold}%                   |
| **Time**     | {readable_time}                 |
| **Detected** | Linux Health Monitor (auto)     |

## What Happened
{metric.upper()} usage reached {current_value}%, exceeding the configured threshold of {threshold}%.

## Immediate Actions Taken
- Alert email sent to on-call
- Incident report auto-generated
- Metric recorded in Prometheus

## Suggested Next Steps
- [ ] Check which processes are consuming the most {metric}
- [ ] Review recent deployments or config changes
- [ ] Check for memory leaks or runaway processes
- [ ] Resolve and update this report with root cause

## Status
- [ ] Investigating
- [ ] Mitigated
- [ ] Resolved

---
*Auto-generated by Linux Health Monitor*
"""

    with open(filename, "w") as f:
        f.write(content)

    print(f"Incident report created: {filename}")
    return filename

if __name__ == "__main__":
    # Testing it
    create_incident_report("cpu", 92, 80)